name: CI Pipeline

on:
  push:
    branches:
      - main  # Run the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the pipeline on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if applicable)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Print a success message
      - name: Notify Success
        run: echo "Tests passed successfully!"

